name: franka
channels:
  - conda-forge
dependencies:
  - python=3.10.19
  - pip
  - git
  - cmake>=3.22,<4
  - ninja
  - make
  - pkg-config
  - cxx-compiler
  - numpy
  - eigen=3.4.0
  - poco
  - fmt
  - libfranka=0.20.5
  - pinocchio=3.9.0
  - eigenpy
  - hpp-fcl
  - coal
  - urdfdom
  - casadi
  - libboost
  - libboost-devel
  - pybind11
  - build
  - exceptiongroup
  - pathspec
  - pyproject_hooks
  - scikit-build-core
  - setuptools
  - setuptools-scm
  - wheel
  - pip:
      - pylibfranka==0.20.5
